[package]
name = "yew-address-book-client"
version = "0.1.0"
authors = ["Hai Phan <bahaimt@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4.14"
strum = "0.20.0"
strum_macros = "0.20.1"
serde = "1.0.123"
serde_derive = "1.0.123"
wasm-bindgen = "0.2.70"
wasm-logger = "0.2.0"
wee_alloc = { version = "0.4.5", optional = true }
yew = "0.17.4"
yew-router = "0.14.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.20"

[dependencies.web-sys]
version = "0.3.47"
features = [
  'KeyboardEvent',
]
