[build]
target = "index.html"
release = true
dist = "server/dist"
public_url = "/"

[serve]
addr = "127.0.0.1"
port = 3000
open = true
no_autoreload = false

[clean]
dist = "server/dist"
cargo = true

[[proxy]]
rewrite = "/api/"
backend = "http://127.0.0.1:8000/api"
