app:
  name: address-book-local
  port: 3000
  max-age: 604800
api:
  backend:
    host: address-book-api-local
    port: 8000
    path: api
db:
  host: address-book-db-local
  port: 5432
  name: postgres
  username: postgres
  password: postgres
