app:
  name: address-book-dev
  port: 3000
  max-age: 604800
api:
  backend:
    host: address-book-api-dev
    port: 8000
    path: api
db:
  host: address-book-db-dev
  port: 5432
  name: address_book_db
  username: postgres
  password: postgres
