app:
  name: address-book-local
  port: 3000
  max-age: 604800
api:
  backend:
    host: 127.0.0.1
    port: 8000
    path: api
db:
  host: 127.0.0.1
  port: 5432
  name: address_book_db
  username: postgres
  password: postgres
